# classifier_tester
# Autogenerated from man page /usr/share/man/man1/classifier_tester.1.gz
complete -c classifier_tester -s l -d '(Input) three character language code; default value eng'
complete -c classifier_tester -o classifier -d '(Input) One of "pruner", "full"'
complete -c classifier_tester -s U -d '(Input) The unicharset for the language'
complete -c classifier_tester -s F -d '(Input) font properties file, each line is of the following form, where each …'
complete -c classifier_tester -s X -d '(Input) x heights file, each line is of the following form, where xheight is …'
complete -c classifier_tester -o output_trainer -d '(Output, Optional) Filename for output trainer'

