# combine_lang_model
# Autogenerated from man page /usr/share/man/man1/combine_lang_model.1.gz
complete -c combine_lang_model -l lang -d 'The language to use.  Tesseract uses 3-character ISO 639-2 language codes'
complete -c combine_lang_model -l script_dir -d 'Directory name for input script unicharsets'
complete -c combine_lang_model -l input_unicharset -d 'Unicharset to complete and use in encoding'
complete -c combine_lang_model -l lang_is_rtl -d 'True if language being processed is written right-to-left (eg Arabic/Hebrew)'
complete -c combine_lang_model -l pass_through_recoder -d 'If true, the recoder is a simple pass-through of the unicharset'
complete -c combine_lang_model -l version_str -d 'An arbitrary version label to add to traineddata file (type:string default:)'
complete -c combine_lang_model -l words -d '(Optional) File listing words to use for the system dictionary (type:string d…'
complete -c combine_lang_model -l numbers -d '(Optional) File listing number patterns (type:string default:)'
complete -c combine_lang_model -l puncs -d '(Optional) File listing punctuation patterns'
complete -c combine_lang_model -l output_dir -d 'Root directory for output files'

