# combine_tessdata
# Autogenerated from man page /usr/share/man/man1/combine_tessdata.1.gz
complete -c combine_tessdata -s c
complete -c combine_tessdata -s d
complete -c combine_tessdata -s e
complete -c combine_tessdata -s l
complete -c combine_tessdata -s o
complete -c combine_tessdata -s u -d CAVEATS

