# fuzzel
# Autogenerated from man page /usr/share/man/man1/fuzzel.1.gz
complete -c fuzzel -l config
complete -c fuzzel -s o -l output
complete -c fuzzel -s f -l font
complete -c fuzzel -s D -l dpi-aware
complete -c fuzzel -s p -l prompt
complete -c fuzzel -s i
complete -c fuzzel -l icon-theme
complete -c fuzzel -s I -l no-icons
complete -c fuzzel -s F -l fields
complete -c fuzzel -l password
complete -c fuzzel -s T -l terminal
complete -c fuzzel -s l -l lines
complete -c fuzzel -s w -l width
complete -c fuzzel -l tabs
complete -c fuzzel -s x -l horizontal-pad
complete -c fuzzel -s y -l vertical-pad
complete -c fuzzel -s P -l inner-pad
complete -c fuzzel -s b -l background
complete -c fuzzel -s t -l text-color
complete -c fuzzel -s m -l match-color
complete -c fuzzel -s s -l selection-color
complete -c fuzzel -s S -l selection-text-color
complete -c fuzzel -s M -l selection-match-color
complete -c fuzzel -s B -l border-width
complete -c fuzzel -s r -l border-radius
complete -c fuzzel -s C -l border-color
complete -c fuzzel -l show-actions
complete -c fuzzel -l filter-desktop
complete -c fuzzel -l no-fuzzy
complete -c fuzzel -l fuzzy-min-length
complete -c fuzzel -l fuzzy-max-length-discrepancy
complete -c fuzzel -l fuzzy-max-distance
complete -c fuzzel -l line-height
complete -c fuzzel -l letter-spacing
complete -c fuzzel -l layer
complete -c fuzzel -l no-exit-on-keyboard-focus-loss
complete -c fuzzel -l launch-prefix
complete -c fuzzel -s d -l dmenu
complete -c fuzzel -l dmenu0
complete -c fuzzel -l index
complete -c fuzzel -s R -l no-run-if-empty
complete -c fuzzel -l log-level
complete -c fuzzel -l log-colorize
complete -c fuzzel -l log-no-syslog
complete -c fuzzel -s v -l version

