# gtklock
# Autogenerated from man page /usr/share/man/man1/gtklock.1.gz
complete -c gtklock -s h -l help -d 'Show help options'
complete -c gtklock -l help-config -d 'Show options available in the config'
complete -c gtklock -s d -l daemonize -d 'Detach from controlling terminal'
complete -c gtklock -s c -l config -d 'Specify config file to use.  By default, the following paths are checked'

