# iscsi-ls
# Autogenerated from man page /usr/share/man/man1/iscsi-ls.1.gz
complete -c iscsi-ls -s i -l initiator-name -d 'This specifies the initiator-name that iscsi-ls will use when logging in to t…'
complete -c iscsi-ls -s s -l show-luns -d 'In addition to listing all the targets at the specified portal also list all …'
complete -c iscsi-ls -s d -l debug -d 'Print debug information'
complete -c iscsi-ls -s '?' -l help -d 'Display basic help text'
complete -c iscsi-ls -l usage -d 'Display basic usage text'

