# iscsi-swp
# Autogenerated from man page /usr/share/man/man1/iscsi-swp.1.gz
complete -c iscsi-swp -s i -l initiator-name -d 'This specifies the initiator-name that iscsi-ls will use when logging in to t…'
complete -c iscsi-swp -s s -l swp -d 'By default iscsi-swp will only print the current setting of the software writ…'
complete -c iscsi-swp -s d -l debug -d 'Debug level'
complete -c iscsi-swp -s '?' -l help -d 'Display basic help text'
complete -c iscsi-swp -l usage -d 'Display basic usage text'

