# iscsi-test-cu
# Autogenerated from man page /usr/share/man/man1/iscsi-test-cu.1.gz
complete -c iscsi-test-cu -s i -l initiator-name -d 'All tests use at least one iSCSI connection to the target and this is the ini…'
complete -c iscsi-test-cu -s I -l initiator-name-2 -d 'Some tests use a second connection to the target, such as the \\*(Aqit nexus l…'
complete -c iscsi-test-cu -s l -l list -d 'This argument lists all available tests'
complete -c iscsi-test-cu -s t -l test -d 'This argument specifies a comma-separated list of the test expressions to run'
complete -c iscsi-test-cu -s d -l dataloss -d 'By default the test tool will only run non-destructive tests'
complete -c iscsi-test-cu -s s -l allow-sanitize -d 'The SBC SANITIZE opcode is expected to take significant time before it comple…'
complete -c iscsi-test-cu -s V -l Verbose-scsi -d 'The tests aims to be self-documenting'
complete -c iscsi-test-cu -s x -l xml -d 'This option to produce test results in machine readable format for automated …'
complete -c iscsi-test-cu -s '?' -l help -d 'Display basic help text'
complete -c iscsi-test-cu -l - -d '+++ b/cunit-to-junit. pl @@ -226,4 +226,4 @@ foreach my $s (@suites)  }'

