# lstmeval
# Autogenerated from man page /usr/share/man/man1/lstmeval.1.gz
complete -c lstmeval -l model -d 'Name of model file (training or recognition) (type:string default:)'
complete -c lstmeval -l traineddata -d 'If model is a training checkpoint, then traineddata must be the traineddata f…'
complete -c lstmeval -l eval_listfile -d 'File listing sample files in lstmf training format.  (type:string default:)'
complete -c lstmeval -l max_image_MB -d 'Max memory to use for images.  (type:int default:2000)'
complete -c lstmeval -l verbosity -d 'Amount of diagnosting information to output (0-2).  (type:int default:1)'

