# mftraining
# Autogenerated from man page /usr/share/man/man1/mftraining.1.gz
complete -c mftraining -s U -d '(Input) The unicharset generated by unicharset_extractor(1)'
complete -c mftraining -s F -d '(Input) font properties file, each line is of the following form, where each …'
complete -c mftraining -s X -d '(Input) x heights file, each line is of the following form, where xheight is …'
complete -c mftraining -s D -d 'Directory to write output files to'
complete -c mftraining -s O -d '(Output) The output unicharset that will be given to combine_tessdata(1)'

