# multipathd
# Autogenerated from man page /usr/share/man/man8/multipathd.8.gz
complete -c multipathd -s d -d 'Foreground Mode'
complete -c multipathd -s s -d 'Suppress timestamps.  Do not prefix logging messages with a timestamp'
complete -c multipathd -s v -d 'Verbosity level.  Print additional information while running multipathd'
complete -c multipathd -s B -d 'Read-only bindings file'
complete -c multipathd -o kcommand -d 'multipathd executes the given command (see COMMANDS below)'
complete -c multipathd -s k -d 'multipathd executes the multipathc interactive shell for entering commands (s…'
complete -c multipathd -s n -d IGNORED
complete -c multipathd -s w -d 'Since kernel 4'

