# pacseek-bin
# Autogenerated from man page /usr/share/man/man1/pacseek-bin.1.gz
complete -c pacseek-bin -s r -d 'Limit searching to a comma separated list of repositories'
complete -c pacseek-bin -s s -d 'Search term when used with the  -r option'
complete -c pacseek-bin -s a -d 'ASCII mode'
complete -c pacseek-bin -s m -d 'Monochrome mode'
complete -c pacseek-bin -s u -d 'Show upgrades after startup'
complete -c pacseek-bin -s i -d 'Show installed packages after startup'
complete -c pacseek-bin -s h -l help -d 'Display help and exit'

