# set_unicharset_properties
# Autogenerated from man page /usr/share/man/man1/set_unicharset_properties.1.gz
complete -c set_unicharset_properties -l script_dir -d '(Input) Specify the location of directory for universal script unicharsets an…'
complete -c set_unicharset_properties -l U -d '(Input) Specify the location of the unicharset to load as input'
complete -c set_unicharset_properties -l O -d '(Output) Specify the location of the unicharset to be written with updated pr…'

