# shapeclustering
# Autogenerated from man page /usr/share/man/man1/shapeclustering.1.gz
complete -c shapeclustering -s U -d 'The unicharset generated by unicharset_extractor(1)'
complete -c shapeclustering -s D -d 'Directory to write output files to'
complete -c shapeclustering -s F -d '(Input) font properties file, where each line is of the following form, where…'
complete -c shapeclustering -s X -d '(Input) x heights file, each line is of the following form, where xheight is …'
complete -c shapeclustering -s O -d 'The output unicharset that will be given to combine_tessdata(1)'

