# svg2pdf
# Autogenerated from man page /usr/share/man/man1/svg2pdf.1.gz
complete -c svg2pdf -s h -l help -d 'show a help message and exit'
complete -c svg2pdf -s v -l version -d 'print version number and exit'
complete -c svg2pdf -s o -l output -d 'Set output path (incl'

