# swww-img
# Autogenerated from man page /usr/share/man/man1/swww-img.1.gz
complete -c swww-img -s f -l filter -d 'Filter to use when scaling images'
complete -c swww-img -l no-resize -d 'Do not resize the image.  Equivalent to --resize no'
complete -c swww-img -l fill-color -d 'Which color to fill the padding with when not resizing'
complete -c swww-img -s o -l outputs -d 'Comma separated list of outputs to display the image at.  Use swww query to'
complete -c swww-img -s t -l transition-type -d '[Environment Variable $SWWW_TRANSITION]'
complete -c swww-img -l transition-step -d '[Environment Variable $SWWW_TRANSITION_STEP]'
complete -c swww-img -l transition-duration -d '[Environment Variable $SWWW_TRANSITION_DURATION]'
complete -c swww-img -l transition-fps -d '[Environment Variable: $SWWW_TRANSITION_FPS]'
complete -c swww-img -l transition-angle -d '[Environment Variable: SWWW_TRANSITION_ANGLE]'
complete -c swww-img -l transition-pos -d '[Environment Variable: SWWW_TRANSITION_POS]'
complete -c swww-img -l invert-y -d '[Environment Variable: SWWW_INVERT_Y]'
complete -c swww-img -l transition-bezier -d '[Environment Variable: SWWW_TRANSITION_BEZIER]'
complete -c swww-img -l transition-wave -d '[Environment Variable: SWWW_TRANSITION_WAVE]'
complete -c swww-img -s h -l help -d 'Print help (see a summary with \'-h\')'

