# swww-clear
# Autogenerated from man page /usr/share/man/man1/swww-clear.1.gz
complete -c swww-clear -s o -l outputs -d 'Comma separated list of outputs to display the image at.  Use swww query to'
complete -c swww-clear -s h -l help -d 'Print help (see a summary with \'-h\')'

