# ydotoold
# Autogenerated from man page /usr/share/man/man8/ydotoold.8.gz
complete -c ydotoold -s p -l socket-path -d 'Set socket path'
complete -c ydotoold -s P -l socket-perm -d 'Set socket permission'
complete -c ydotoold -s h -l help -d 'Display help and exit'

