# ydotool
# Autogenerated from man page /usr/share/man/man1/ydotool.1.gz
complete -c ydotool -s d -l key-delay
complete -c ydotool -s D -l next-delay
complete -c ydotool -s f -l file
complete -c ydotool -l absolute
complete -c ydotool -s r -l repeat

